# Use root/example as user/password credentials
version: '3.9'

services:

  db:
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: dbname
      MYSQL_ROOT_PASSWORD: supersecret

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  api:
    build:
      context: .
      args:
        - APP_HOST=0.0.0.0
        - APP_PORT=8000
    ports:
      - "8000:8000"
    environment:
      ENV: "development"
      DATABASE_URL: "mysql+pymysql://root:supersecret@db:3306/dbname"
      APP_HOST: "0.0.0.0"
      APP_PORT: "8000"
    depends_on:
      - db
    restart: on-failure
